# Generated by Django 5.2.6 on 2025-11-06 03:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True)),
                ('logo', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('total_projects', models.IntegerField(default=0)),
                ('completed_projects', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'db_table': 'developers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('mixed', 'Mixed Use'), ('plotted', 'Plotted Development')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('paused', 'Paused')], default='upcoming', max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_units', models.IntegerField(default=0)),
                ('available_units', models.IntegerField(default=0)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('expected_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('total_floors', models.IntegerField(blank=True, null=True)),
                ('total_area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('views_count', models.IntegerField(default=0)),
                ('interested_count', models.IntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.developer')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phase_number', models.IntegerField()),
                ('target_date', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ai_verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('images', models.JSONField(blank=True, default=list)),
                ('videos', models.JSONField(blank=True, default=list)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_milestones', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'verbose_name': 'Construction Milestone',
                'verbose_name_plural': 'Construction Milestones',
                'db_table': 'construction_milestones',
                'ordering': ['project', 'phase_number'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.CharField(max_length=50)),
                ('property_type', models.CharField(choices=[('1bhk', '1 BHK'), ('2bhk', '2 BHK'), ('3bhk', '3 BHK'), ('4bhk', '4 BHK'), ('5bhk+', '5 BHK+'), ('studio', 'Studio Apartment'), ('penthouse', 'Penthouse'), ('villa', 'Villa'), ('plot', 'Plot'), ('shop', 'Shop'), ('office', 'Office Space')], max_length=20)),
                ('floor_number', models.IntegerField(blank=True, null=True)),
                ('tower', models.CharField(blank=True, max_length=50, null=True)),
                ('carpet_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('super_built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('balconies', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('sold', 'Sold'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('features', models.JSONField(blank=True, default=list)),
                ('floor_plan_image', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.project')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['project', 'floor_number', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('location_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('amenities_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('value_rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('helpful_count', models.IntegerField(default=0)),
                ('verified_buyer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'project_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['city', 'status'], name='projects_city_9d4812_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['developer', 'status'], name='projects_develop_38e17b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['starting_price'], name='projects_startin_32abed_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['project', 'status'], name='constructio_project_0a26db_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionmilestone',
            index=models.Index(fields=['target_date'], name='constructio_target__980626_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('project', 'unit_number')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('project', 'user')},
        ),
    ]
