# Generated by Django 5.2.6 on 2025-11-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_project_videos_project_qr_code_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionmilestone',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='constructionmilestone',
            name='qr_code_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='qr_code_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
