# Generated by Django 5.2.6 on 2025-11-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_construction_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='constructionupdate',
            new_name='constructio_project_17ae5e_idx',
            old_name='constructio_project_idx',
        ),
        migrations.RenameIndex(
            model_name='constructionupdate',
            new_name='constructio_project_541d1f_idx',
            old_name='constructio_project_unit_idx',
        ),
    ]
