# Generated by Django 5.2.6 on 2025-11-16 09:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_rename_constructio_project_idx_constructio_project_17ae5e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('token_paid', 'Token Paid'), ('confirmed', 'Confirmed'), ('agreement_pending', 'Agreement Pending'), ('agreement_signed', 'Agreement Signed'), ('payment_in_progress', 'Payment In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], default='pending', max_length=30)),
                ('property_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('token_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_schedule', models.JSONField(blank=True, default=dict)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('token_payment_date', models.DateTimeField(blank=True, null=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('agreement_date', models.DateTimeField(blank=True, null=True)),
                ('expected_possession_date', models.DateField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=50, null=True)),
                ('agreement_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('agreement_document_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_documents', models.JSONField(blank=True, default=list)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('cancellation_initiated_by', models.CharField(blank=True, max_length=20, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=50, null=True)),
                ('refund_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('special_conditions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='projects.property')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-booking_date'],
                'indexes': [models.Index(fields=['property', 'status'], name='bookings_propert_933c8e_idx'), models.Index(fields=['buyer', 'status'], name='bookings_buyer_i_57833b_idx'), models.Index(fields=['booking_number'], name='bookings_booking_502bea_idx'), models.Index(fields=['booking_date'], name='bookings_booking_2846e7_idx'), models.Index(fields=['status'], name='bookings_status_51373b_idx')],
            },
        ),
    ]
