# Generated by Django 5.2.6 on 2025-11-16 10:27

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_create_payment_models'),
        ('projects', '0011_add_booking_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProperty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_tokens', models.IntegerField(help_text='Total number of tokens', validators=[django.core.validators.MinValueValidator(1)])),
                ('token_price', models.DecimalField(decimal_places=2, help_text='Price per token', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('available_tokens', models.IntegerField(default=0, help_text='Available tokens for purchase')),
                ('sold_tokens', models.IntegerField(default=0, help_text='Tokens already sold')),
                ('minimum_investment', models.DecimalField(decimal_places=2, help_text='Minimum investment amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('maximum_investment_per_user', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum investment per user (optional)', max_digits=12, null=True)),
                ('revenue_share_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentage of revenue shared with investors', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('dividend_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='quarterly', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('tokenizing', 'Tokenizing'), ('active', 'Active'), ('fully_subscribed', 'Fully Subscribed'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('tokenization_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_property', to='projects.property')),
            ],
            options={
                'verbose_name': 'Investment Property',
                'verbose_name_plural': 'Investment Properties',
                'db_table': 'investment_properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokens', models.IntegerField(help_text='Number of tokens purchased', validators=[django.core.validators.MinValueValidator(1)])),
                ('token_price', models.DecimalField(decimal_places=2, help_text='Price per token at purchase', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total investment amount', max_digits=12)),
                ('current_token_price', models.DecimalField(blank=True, decimal_places=2, help_text='Current token price', max_digits=12, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Current investment value', max_digits=12, null=True)),
                ('total_dividends_received', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total dividends received', max_digits=12)),
                ('total_return', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Total return (dividends + capital gains)', max_digits=12)),
                ('return_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Return percentage', max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('investment_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investments.investmentproperty')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'db_table': 'investments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_per_token', models.DecimalField(decimal_places=2, help_text='Dividend amount per token', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total dividend amount', max_digits=12)),
                ('tokens_eligible', models.IntegerField(help_text='Number of tokens eligible for dividend')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dividends', to=settings.AUTH_USER_MODEL)),
                ('investment_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='investments.investmentproperty')),
            ],
            options={
                'verbose_name': 'Dividend',
                'verbose_name_plural': 'Dividends',
                'db_table': 'dividends',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('transfer', 'Transfer')], max_length=20)),
                ('tokens', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('token_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
                ('investment_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investmentproperty')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transactions', to='payments.payment')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Transaction',
                'verbose_name_plural': 'Investment Transactions',
                'db_table': 'investment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tokens', models.IntegerField(help_text='Number of tokens eligible for this dividend')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Dividend amount', max_digits=12)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dividend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='investments.dividend')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dividend_payments', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_payments', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_payments', to='investments.investment')),
            ],
            options={
                'verbose_name': 'Dividend Payment',
                'verbose_name_plural': 'Dividend Payments',
                'db_table': 'dividend_payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='dividend_pa_user_id_99a75e_idx'), models.Index(fields=['dividend', 'status'], name='dividend_pa_dividen_661f98_idx'), models.Index(fields=['investment', 'status'], name='dividend_pa_investm_45ad1b_idx')],
                'unique_together': {('dividend', 'investment')},
            },
        ),
        migrations.AddIndex(
            model_name='investmentproperty',
            index=models.Index(fields=['status', 'created_at'], name='investment__status_fd02d1_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentproperty',
            index=models.Index(fields=['property'], name='investment__propert_649f95_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'status'], name='investments_user_id_dfa5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['investment_property', 'status'], name='investments_investm_101782_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['status', 'created_at'], name='investments_status_9fccfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('investment_property', 'user')},
        ),
        migrations.AddIndex(
            model_name='dividend',
            index=models.Index(fields=['investment_property', 'status'], name='dividends_investm_9e3d69_idx'),
        ),
        migrations.AddIndex(
            model_name='dividend',
            index=models.Index(fields=['status', 'payment_date'], name='dividends_status_3aca43_idx'),
        ),
        migrations.AddIndex(
            model_name='dividend',
            index=models.Index(fields=['period_start', 'period_end'], name='dividends_period__cecea5_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['user', 'status'], name='investment__user_id_d31481_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['investment_property', 'transaction_type'], name='investment__investm_5ce646_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='investment__status_dadf70_idx'),
        ),
    ]
