# Generated by Django 5.2.6 on 2025-11-15 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0010_rename_constructio_project_idx_constructio_project_17ae5e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainDocument',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(max_length=255, unique=True)),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('agreement', 'Agreement'), ('certificate', 'Certificate'), ('permit', 'Permit'), ('license', 'License'), ('other', 'Other')], max_length=50)),
                ('ipfs_hash', models.CharField(max_length=255)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_timestamp', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_documents', to='projects.project')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_documents', to='projects.property')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Document',
                'verbose_name_plural': 'Blockchain Documents',
                'db_table': 'blockchain_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockchainProgressUpdate',
            fields=[
                ('id', models.UUIDField(default=None, editable=False, primary_key=True, serialize=False)),
                ('progress_id', models.CharField(max_length=255, unique=True)),
                ('milestone_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ipfs_hash', models.CharField(max_length=255)),
                ('blockchain_tx_id', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_timestamp', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_progress', to='projects.project')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blockchain_progress', to='projects.property')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Progress Update',
                'verbose_name_plural': 'Blockchain Progress Updates',
                'db_table': 'blockchain_progress_updates',
                'ordering': ['-created_at'],
            },
        ),
    ]
