# Generated by Django 5.2.6 on 2025-11-16 10:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('date', models.DateField()),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_projects', models.IntegerField(default=0)),
                ('new_projects', models.IntegerField(default=0)),
                ('project_views', models.IntegerField(default=0)),
                ('total_properties', models.IntegerField(default=0)),
                ('available_properties', models.IntegerField(default=0)),
                ('booked_properties', models.IntegerField(default=0)),
                ('sold_properties', models.IntegerField(default=0)),
                ('property_views', models.IntegerField(default=0)),
                ('total_bookings', models.IntegerField(default=0)),
                ('new_bookings', models.IntegerField(default=0)),
                ('confirmed_bookings', models.IntegerField(default=0)),
                ('cancelled_bookings', models.IntegerField(default=0)),
                ('completed_bookings', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('booking_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('token_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pending_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_payments', models.IntegerField(default=0)),
                ('completed_payments', models.IntegerField(default=0)),
                ('failed_payments', models.IntegerField(default=0)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('booking_conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('payment_conversion_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage', max_digits=5)),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('avg_session_duration', models.IntegerField(default=0, help_text='In seconds')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Metric',
                'verbose_name_plural': 'Analytics Metrics',
                'db_table': 'analytics_metrics',
                'ordering': ['-date', '-metric_type'],
                'indexes': [models.Index(fields=['metric_type', 'date'], name='analytics_m_metric__94423b_idx'), models.Index(fields=['date'], name='analytics_m_date_7cb4c5_idx')],
                'unique_together': {('metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('project_view', 'Project View'), ('property_view', 'Property View'), ('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_completed', 'Payment Completed'), ('payment_failed', 'Payment Failed'), ('user_registered', 'User Registered'), ('user_login', 'User Login'), ('search_performed', 'Search Performed'), ('filter_applied', 'Filter Applied'), ('document_viewed', 'Document Viewed'), ('document_downloaded', 'Document Downloaded'), ('contact_form_submitted', 'Contact Form Submitted'), ('other', 'Other')], max_length=50)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_e_event_t_c3dcde_idx'), models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_7e4ee5_idx'), models.Index(fields=['related_object_type', 'related_object_id'], name='analytics_e_related_48826a_idx'), models.Index(fields=['created_at'], name='analytics_e_created_3bce1d_idx'), models.Index(fields=['session_id', 'created_at'], name='analytics_e_session_283fe0_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('user_report', 'User Report'), ('project_report', 'Project Report'), ('booking_report', 'Booking Report'), ('revenue_report', 'Revenue Report'), ('performance_report', 'Performance Report'), ('custom', 'Custom Report')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analytics Report',
                'verbose_name_plural': 'Analytics Reports',
                'db_table': 'analytics_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['report_type', 'created_at'], name='analytics_r_report__e5e6c6_idx'), models.Index(fields=['generated_by', 'created_at'], name='analytics_r_generat_081f98_idx'), models.Index(fields=['is_archived', 'created_at'], name='analytics_r_is_arch_685336_idx')],
            },
        ),
    ]
