# Generated by Django 5.2.6 on 2025-10-31 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_setup_site'),
        ('users', '0004_setup_site'),
    ]

    operations = [
    ]
