# Generated by Django 5.2.6 on 2025-11-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_0003_setup_site_0004_setup_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recently_viewed',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_projects',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
